### PR TITLE
Fix pub: not found error when flutter_package: false #32

### LINKED ISSUE #32: pub: not found error when flutter_package: false
action.yml
```yaml
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.0
        with:
          credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: ${{ github.ref != 'refs/heads/master' }}
          package_directory: ./h3_dart
```

log.txt
```sh
Check credentials
OK
Copy credentials
/home/cirrus/entrypoint.sh: 65: pub: not found
OK
Switching to package directory
Skip test
Executing package validation
```

### PR DESCRIPTION
**Pull request by festelo**
Resolves #32

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -52,24 +52,22 @@ run_test_if_needed() {
 }
 
 create_prefix() {
-  FLUTTER_PREFIX=""
-  PUB_PREFIX="pub"
```
Comment (CaseyHillers) [inline entrypoint.sh:56]: Is there a difference between `dart pub` and `flutter pub`? It would be simpler to have `PUB_PREFIX="dart pub"` and use that everywhere

**Comment by sakebook** [comment]
@festelo 

Thank you. LGTM 👍

File: entrypoint.sh (hunk 1 above)
Comment (sakebook) [reply entrypoint.sh:56]: @CaseyHillers 

I think you said right. https://github.com/flutter/flutter/issues/88507
I will fix the next release.
